//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StarWarsLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class Attaque
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Attaque()
        {
            this.Combat = new HashSet<Combat>();
        }
    
        public int ID { get; set; }
        public Nullable<System.DateTime> DateDebut { get; set; }
        public Nullable<System.DateTime> DateFin { get; set; }
        public Nullable<bool> Victorieux { get; set; }
        public Nullable<int> NbWookies { get; set; }
        public Nullable<int> NbDroides { get; set; }
        public Nullable<int> PlaneteID { get; set; }
    
        public virtual Planete Planete { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Combat> Combat { get; set; }
    }
}
