//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StarWarsLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class Droide
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Droide()
        {
            this.Combat = new HashSet<Combat>();
        }
    
        public int ID { get; set; }
        public string Matricule { get; set; }
        public System.DateTime DateF { get; set; }
        public int PointsDeVie { get; set; }
        public Nullable<int> ModeleID { get; set; }
    
        public virtual Modele Modele { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Combat> Combat { get; set; }
    }
}
